---
title: "COMPSCIX 415.2 Homework 1"
author: "Sharmistha Maitra"
date: "2/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

My Github repository for my assignments can be found at this URL: [https://github.com/sharmisthamaitra/compscix-415-2-assignments](your URL)

library(mdsr)
library(tidyverse)
'''{r load_packages, warning=FALSE, message=FALSE}

data("WorldCities")

glimpse(WorldCities)

WorldCities <- head(WorldCities, 200) # 200 rows

country_col <- WorldCities$country
unique(country_col)

##QUESTION 2: There is a column called region in the data set. Can you extract this and show only the unique values?
region_col <- WorldCities$region
unique(region_col)


WorldCities %>% select(region) %>% head(5)


##QUESTION 3: Can you extract and show the unique entries from the country column in WorldCities using one line of code and two %>% operators?
WorldCities %>% select(country) %>% unique


WorldCities %>% ggplot(aes(x = population)) +
geom_histogram()
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.

WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
xlab('City Population')


##QUESTION 4: Make one more histogram of the population and add a new x-label, a new ylabel, a new title (use ggtitle('my title')), and change the theme of the plot using theme_bw().
WorldCities %>% ggplot(aes(x = population)) +
geom_histogram() +
xlab('City Population') +
ylab('Population Count') +
ggtitle('World Cities Population Chart', subtitle = NULL) +
theme_bw()


